[project]
name = "repl"
version = "0.1.0"
description = "A simple REPL application."
authors = ["N. E. Davis <neal@zorp.io>"]
license = "MIT"
repository = "https://github.com/sigilante/repl"
homepage = "https://github.com/sigilante/repl"
keywords = ["nockapp", "nockchain", "hoon"]
edition = "2021"
template = "basic"
