manifest-version = "1"
date = "2025-08-25"

[pkg.hoonc]
version = "0.2.0"
components = ["core"]

[pkg.hoonc.target.x86_64-unknown-linux-gnu]
available = true
url = "https://github.com/sigilante/nockchain/releases/download/stable-build-{commit}/hoonc-stable-0.2.0-x86_64-unknown-linux-gnu.tar.gz"
hash_blake3 = "{hash_blake3}"
hash_sha1 = "{hash_sha1}"

[pkg.hoonc.target.aarch64-apple-darwin]
available = true
url = "https://github.com/sigilante/nockchain/releases/download/stable-build-{commit}/hoonc-stable-0.2.0-aarch64-apple-darwin.tar.gz"
hash_blake3 = "{hash_blake3}"
hash_sha1 = "{hash_sha1}"