manifest-version = "1"
date = "2025-08-25"

[pkg.nockup]
version = "0.1.0"
components = ["core"]
extensions = []

[pkg.nockup.target.x86_64-unknown-linux-gnu]
available = true
url = "https://github.com/sigilante/nockchain/releases/download/stable-build-{commit}/nockup-stable-0.3.0-x86_64-unknown-linux-gnu.tar.gz"
hash_blake3 = "{hash_blake3}"
hash_sha1 = "{hash_sha1}"

[pkg.nockup.target.aarch64-apple-darwin]
available = true
url = "https://github.com/sigilante/nockchain/releases/download/stable-build-{commit}/nockup-stable-0.3.0-aarch64-apple-darwin.tar.gz"
hash_blake3 = "{hash_blake3}"
hash_sha1 = "{hash_sha1}"